# Generated by cucumber-sinatra. (2012-04-18 15:14:04 -0300)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/lizard_spock.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = LizardSpock

class LizardSpockWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  LizardSpockWorld.new
end
